name: Demo 6 - Custom Workflow

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

runs: 
  using: "composite"  # https://docs.github.com/es/actions/creating-actions/about-custom-actions
  steps:
    - run: echo Hello workflow Reusable
      shell: bash
# jobs:
#   test5:
#     runs-on: ubuntu-latest
#     # needs: [build, deploy]
#     steps:
#       - run: echo Hello actions Reusable
#         shell: bash
      # - uses: ./reusable-action
      #   with:
      #     URL: "https://www.google.cl"