name: Demo 5 - Custom Workflow


on:
  push:
    branches: [master]
# on:
#   workflow_call:
#     inputs:
#       username:
#         required: false
#         type: string


jobs:
  test5:
    runs-on: ubuntu-latest
    # needs: [build, deploy]
    steps:
      - uses: actions/checkout@v1
      - uses: ./reusable-action
        # with:
        #   URL: "https://www.google.cl"