name: Demo 6 - Custom Workflow

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      # - run: echo Hello workflow Reusable
      #   shell: bash
      - uses: actions/checkout@v1
      - uses: /reusable-action/action

