name: Demo 4 - Custom Workflow

on:
  push:
    branches: [master]


jobs:
  test4:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        url: ["https://www.mezcladigital.com/", "https://www.mezcladigital.com/educacion", "https://mezcladigital.com/programas/"]
      # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    # needs: [build, deploy]
    steps:
      - uses: actions/checkout@v1
      - uses: ./security-action
        with:
          URL: ${{ matrix.url }}