name: Demo 6 - Custom Workflow

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - run: echo Hello workflow Reusable
        shell: bash
      - uses: franciscomoli/docker-test-action/reusable-action

# jobs:
#   test5:
#     runs-on: ubuntu-latest
#     # needs: [build, deploy]
#     steps:
#       - run: echo Hello actions Reusable
#         shell: bash
      # - uses: ./reusable-action
      #   with:
      #     URL: "https://www.google.cl"