name: Demo 6 - Custom Workflow reusable action llamado desde fuera del repo

on: [workflow_call]
  # workflow_call:
    # inputs:
    #   URL:
    #     required: false
    #     type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    # needs: [build, deploy]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: action local
        uses: ./.github/actions/reusable-action
      # - name: Run Gitleaks
      #   uses: eeveebank/github-actions-gitleaks@v1.0.0
      #   with:
      #     depth: 1
      # - uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: gitleaks.sarif
