name: Demo 6 - Custom Workflow reusable action llamado desde fuera del repo

on:
  workflow_call:
    # inputs:
    #   URL:
    #     required: false
    #     type: string

jobs:
  eusable_workflow_job:
    runs-on: ubuntu-latest
    # needs: [build, deploy]
    steps:
      # - uses: actions/checkout@v1
      - uses:  ./.github/workflows/my-action
        with:
          URL: "https://www.google.cl"

