name: Demo 7 - Custom Workflow container node

on:
  push:
    branches: [master]


jobs:

  node_install:
    runs-on: ubuntu-latest
    container:
          image: node:14.16
          env:
            NODE_ENV: development
          ports:
            - 80
          volumes:
            - my_docker_volume:/volume_mount
          options: --cpus 1
    steps:
      - uses: actions/checkout@v1
      - name: Print messages
        run: |
          echo Welcome to Node 
      - name: Install dependencies
        run: npm install